# Use the README file as a reference to customize settings.

Article:
  fields:
    default: title, des, text, view, author, mini_img, add_time
    form: title, des, text, view, author, mini_img, add_time
  relationships: 
  application: Application
