# Use the README file as a reference to customize settings.

User:
  fields:
    default: name, password_digest, who, org, phones, mail, image_url, vacancies_added, resumes_added, courses_added, article_added
    form: name, password_digest, who, org, phones, mail, image_url, vacancies_added, resumes_added, courses_added, article_added
  relationships: 
  application: Application
